---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms: 
  - name: centos7 
    driver_config: 
      dockerfile: test/Dockerfile
      provision_command:
      - echo 'root:P@ssw0rd' | chpasswd
      - mkdir /root/.ssh

suites:
  - name: loadbalancer
    driver_config:
     hostname: nginx-lb
     instance_name: nginx-lb
     forward:
          - 8080:80
     links:
        - web-app.node-1:web-app.node-1
        - web-app.node-2:web-app.node-2
    run_list:
      - recipe[web-app::server]
  - name: web-app-1
    driver_config:
     hostname: web-app.node-1
     instance_name: web-app.node-1
    run_list:
      - recipe[web-app]
  - name: web-app-2
    driver_config:
     hostname: web-app.node-2
     instance_name: web-app.node-2
    run_list:
      - recipe[web-app]



